
CREATE TABLE "HR"."DEPT"
(
	DEPTNO NUMBER(2),
	DNAME VARCHAR2(14 BYTE),
	LOC VARCHAR2(13 BYTE)
)

CREATE TABLE "HR"."EMP"
(
EMPNO NUMBER(4),
ENAME VARCHAR2(10 BYTE),
JOB VARCHAR2(9 BYTE),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2)
)

CREATE TABLE "HR".SALGRADE
(
GRADE NUMBER,
LOSAL NUMBER,
HISAL NUMBER
)

ALTER TABLE "HR".DEPT ADD (
CONSTRAINT PK_DEPT
PRIMARY KEY
(DEPTNO))
 
ALTER TABLE "HR".EMP ADD (
CONSTRAINT PK_EMP
PRIMARY KEY
(EMPNO))

ALTER TABLE "HR".EMP ADD (
CONSTRAINT FK_DEPTNO
FOREIGN KEY (DEPTNO)
REFERENCES "HR".DEPT (DEPTNO))

SELECT * FROM HR.emp

SELECT deptno FROM HR.EMP

SELECT DISTINCT deptno FROM HR.emp

SELECT ename, sal*12 AS yearsal FROM hr.emp

SELECT * FROM hr.emp
ORDER BY sal DESC

SELECT * FROM hr.emp 
WHERE deptno=30
ORDER BY empno DESC 

SELECT * FROM hr.emp 
WHERE NOT deptno=30
ORDER BY empno DESC 

select * from hr.emp where ename like '_L%'

select * from hr.emp where ename like '%AM%'

CREATE TABLE hr.dept_temp2 AS
SELECT * FROM hr.dept

UPDATE hr.dept_temp2 SET loc='SEOUL'

