CREATE TABLE HR."COMMENT" (
	COMMENT_NO NUMBER(38,0) NULL,
	WRITER VARCHAR2(100) NULL,
	POST_NO VARCHAR2(100) NULL,
	CONTENT VARCHAR2(100) NULL,
	CONSTRAINT COMMENT_PK PRIMARY KEY (COMMENT_NO)
);

CREATE TABLE "HR"."POST"(
POST_NO NUMBER (38,0) PRIMARY KEY,
TITLE VARCHAR2 (100),
CONTENT VARCHAR2 (100),
WRITER VARCHAR2 (100),
SCORE NUMBER (38,0),
WRITE_DATE DATE,
POST_CATEGORY VARCHAR2(100)
)



CREATE TABLE "HR"."RESERVATION"
   (	"R_NUM" NUMBER(38,0),
	"R_ID" VARCHAR2(100),
	"R_PEOPEL" VARCHAR2(100),
	"R_PLACE" VARCHAR2(100),
	"R_TIME" VARCHAR2(100),
	 CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("R_NUM")
);

CREATE TABLE PLACE(
PLACE_CODE varchar2(100) PRIMARY KEY,
PLACE_NAME varchar2(100),
PLACE_LOCATION varchar2(100),
PLACE_GRADE float(10),
PLACE_CATEGORY varchar2(100)
)

CREATE TABLE "HR"."MEMBERS"
(	"ID" VARCHAR2(100),
	"PW" VARCHAR2(100),
	"NAME" VARCHAR2(100),
	"AGE" NUMBER(38,0),
	"MEM_ADDR" VARCHAR2(100),
	 CONSTRAINT "MEMBERS_PK" PRIMARY KEY ("ID")
)
	 
	 